### ISSUE TITLE
服务端跑不起来

### ISSUE THREAD

**Issue by kaiwenxiao** [YoRenChen/skeleton-screen-demo#2]
D:\nodejs\node.exe C:\Users\xiao\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js run start:server
yarn run v1.22.18
$ node ./ske && node nodeScript/index
D:\skeleton-screen-demo-master\skeletonjs\script\main.js
D:\skeleton-screen-demo-master\skeletonjs\script\index.js
⬡ pswp: -----  生成开始  -----
[22:26:41] ⬡ pswp:  Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (856583)
.
    at ChromeLauncher.launch (D:\skeleton-screen-demo-master\node_modules\puppeteer\lib\cjs\puppeteer\node\Launcher.js:80:27)
    at async Skeleton.initialize (D:\skeleton-screen-demo-master\skeletonjs\skeleton.js:29:22)
    at async Skeleton.renderRoutes (D:\skeleton-screen-demo-master\skeletonjs\skeleton.js:253:24)
    at async SkeletonMemoryHandle.getSkeletonScreens (D:\skeleton-screen-demo-master\skeletonjs\index.memory.js:37:31)
    at async SkeletonMemoryHandle.init (D:\skeleton-screen-demo-master\skeletonjs\index.memory.js:27:5)
generate skeleton screen failed.
⬡ pswp: -----  生成结束  ------
node:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'D:\skeleton-screen-demo-master\dist\index.html'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.<anonymous> (D:\skeleton-screen-demo-master\nodeScript\server.js:8:21)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\skeleton-screen-demo-master\nodeScript\index.js:1:13) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'D:\\skeleton-screen-demo-master\\dist\\index.html'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Process finished with exit code 1

**Comment by YoRenChen** [comment]
HI !
我测试了一下代码稍微改了下逻辑，让我们能运行起来。
确保 puppeteer 能下载成功，我更新了puppeteer版本，更新下代码即可
运行`npx run serve`，在确保npx serve运行情况下再运行 `npx run start`
访问 localhost 8082 端口，请使用 network slow 3G 下查看 或者使用 performance，刷新时记得无缓存刷新~
希望能帮助到你
